### ISSUE TITLE
RuntimeError: expected device cuda:0 but got device cpu (CUDA 10.1, Pytorch 1.5.1, Windows 10)

### ISSUE THREAD

**Issue by jasha64** [oshears/fpga_snn_models#1]
I ran into a problem when running `./snn_simulation.py` on CUDA 10.1 and Pytorch 1.5.1 in Windows 10:
```
Traceback (most recent call last):
  File "snn_simulation.py", line 194, in <module>
    accuracy["all"].append( 100 * torch.sum(label_tensor.long() == all_activity_pred).item() / len(label_tensor) )
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\tensor.py", line 28, in wrapped
    return f(*args, **kwargs)
RuntimeError: expected device cuda:0 but got device cpu
```

However, if I try adding `.to(device)` to relevant code, i.e.:
```
        # get network predictions based on the spiking activity, previous assignments and number of classes
        all_activity_pred = all_activity( spikes=spike_record, assignments=assignments, n_labels=n_classes ).to(device)

        # get network predictions based on the spiking activity, previous assignments, proportional assignments and number of classes
        proportion_pred = proportion_weighting( spikes=spike_record, assignments=assignments, proportions=proportions, n_labels=n_classes, ).to(device)
```
then the error still occurs, though in the opposite direction:
```
  File "snn_simulation.py", line 191, in <module>
    proportion_pred = proportion_weighting( spikes=spike_record, assignments=assignments, proportions=proportions, n_labels=n_classes, ).to(device)
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\bindsnet\evaluation\evaluation.py", line 167, in proportion_weighting
    torch.sum((proportions[:, i] * spikes)[:, indices], 1) / n_assigns
RuntimeError: expected device cpu but got device cuda:0
```

Furthermore, I tried switching to CUDA 11.3 and Pytorch 1.8.0, only to see the same error occur: "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"

Would you please provide the version of CUDA and Pytorch that I should use? Thank you

**Comment by jasha64** [comment]
Oh, plus one problem: 
```
Traceback (most recent call last):
  File "snn_simulation.py", line 174, in <module>
    for step, batch in enumerate(train_dataloader):
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\bindsnet\datasets\torchvision_wrapper.py", line 80, in __getitem__
    "encoded_image": self.image_encoder(image),
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\bindsnet\encoding\encoders.py", line 18, in __call__
    return self.enc(img, *self.enc_args, **self.enc_kwargs)
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\bindsnet\encoding\encodings.py", line 118, in poisson
    dist = torch.distributions.Poisson(rate=rate)
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributions\poisson.py", line 44, in __init__
    super(Poisson, self).__init__(batch_shape, validate_args=validate_args)
  File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributions\distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter rate has invalid values
```
And I modified `Python\Python37\lib\site-packages\torch\distributions\poisson.py:27` to `arg_constraints = {'rate': constraints.greater_than_eq(0.)}` and bypassed the problem.

**Comment by oshears** [comment]
> I ran into a problem when running `./snn_simulation.py` on CUDA 10.1 and Pytorch 1.5.1 in Windows 10:
> 
> ```
> Traceback (most recent call last):
>   File "snn_simulation.py", line 194, in <module>
>     accuracy["all"].append( 100 * torch.sum(label_tensor.long() == all_activity_pred).item() / len(label_tensor) )
>   File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\tensor.py", line 28, in wrapped
>     return f(*args, **kwargs)
> RuntimeError: expected device cuda:0 but got device cpu
> ```
> 
> However, if I try adding `.to(device)` to relevant code, i.e.:
> 
> ```
>         # get network predictions based on the spiking activity, previous assignments and number of classes
>         all_activity_pred = all_activity( spikes=spike_record, assignments=assignments, n_labels=n_classes ).to(device)
> 
>         # get network predictions based on the spiking activity, previous assignments, proportional assignments and number of classes
>         proportion_pred = proportion_weighting( spikes=spike_record, assignments=assignments, proportions=proportions, n_labels=n_classes, ).to(device)
> ```
> 
> then the error still occurs, though in the opposite direction:
> 
> ```
>   File "snn_simulation.py", line 191, in <module>
>     proportion_pred = proportion_weighting( spikes=spike_record, assignments=assignments, proportions=proportions, n_labels=n_classes, ).to(device)
>   File "C:\Users\jasha\AppData\Local\Programs\Python\Python37\lib\site-packages\bindsnet\evaluation\evaluation.py", line 167, in proportion_weighting
>     torch.sum((proportions[:, i] * spikes)[:, indices], 1) / n_assigns
> RuntimeError: expected device cpu but got device cuda:0
> ```
> 
> Furthermore, I tried switching to CUDA 11.3 and Pytorch 1.8.0, only to see the same error occur: "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"
> 
> Would you please provide the version of CUDA and Pytorch that I should use? Thank you

I have to work on fixing the device switching between CPU and GPU mode for this code. I think a temporary solution could be to remove all of the CUDA/GPU setup code and only use the CPU.

**Comment by oshears** [comment]
>     for step, batch in enumerate(train_dataloader):

This problem is interesting. I think it has to do with the version of PyTorch you have loaded. I'm glad you were able to circumvent it for now, but it may be worth verifying that you have the latest version (I think I'm using 1.10).
